### ISSUE TITLE
What are the commands?

### ISSUE THREAD

**Issue by jamesbrady226** [imDMK/AutoMessage#11]
I've been looking everywhere I can't find any commands for this plugin.

**Comment by imDMK** [comment]
Hello, 
First, check whether the plugin has been launched correctly in two ways: 
- Check the logs in the console when starting the server, no cxy error was displayed. 
- Type the /plugins command and see if the plugin name (AutoMessage) is green. 
And let me know. 

Thanks for installing the plugin, best regards.
