### ISSUE TITLE
How can i make a new line in the automessage chat config?

### ISSUE THREAD

**Issue by TSERATO** [imDMK/AutoMessage#13]
Hello, how can i make a new line for the auto chat message?
This is how i want it to look:
![grafik](https://github.com/imDMK/AutoMessage/assets/106665507/bfd1138e-fd92-49c4-a629-5d7a89d620e6)

And this is how it acctually looks:
![grafik](https://github.com/imDMK/AutoMessage/assets/106665507/f618f15f-dbc4-4146-a7e1-ada101313b18)

Thank You!

**Comment by imDMK** [comment]
Hello,
Thank you for the issue.

To make a new line use character "\n".
Example:
- First line\nSecond line

Best regards.

**Comment by TimeToShine6308** [comment]
Thank You very much!

**Comment by TimeToShine6308** [comment]
Sorry to bother, but \n doesnt seem to work:
![grafik](https://github.com/imDMK/AutoMessage/assets/106665507/3067bf23-e278-434e-a83f-2fb8da88a52b)
It only started a new line, because the message got too long.

**Comment by imDMK** [comment]
Okay, I understand.
I will soon add this option in the latest plugin update.
Best regards.
